---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-postgres
      # postgres_port: 6543
      postgres_databases:
        - name: test_db
          state: present
      postgres_users:
        - name: test_user_with_pass
          password: "MyCoMpLeXpAsSwOrD"
        - name: test_user_with_db
          password: "MyCoMpLeXpAsSwOrD"
          db: test_db
      postgres_hba_entries:
        - type: local
          database: all
          user: all
          method: peer
        - type: host
          database: all
          user: all
          address: "127.0.0.1/32"
          method: ident
        - type: host
          database: all
          user: all
          address: "::1/128"
          method: ident
        - type: local
          database: replication
          user: all
          method: peer
        - type: host
          database: replication
          user: all
          address: "127.0.0.1/32"
          method: ident
        - type: host
          database: replication
          user: all
          address: "::1/128"
          method: ident
